.TH CLYCOIN-CLI "1" "June 2016" "clycoin-cli 0.12"
.SH NAME
clycoin-cli \- a remote procedure call client for CLY Coin. 
.SH SYNOPSIS
clycoin-cli [options] <command> [params] \- Send command to CLY Coin. 
.TP
clycoin-cli [options] help \- Asks CLY Coin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the clycoin-cli program. clycoin-cli is an RPC client used to send commands to CLY Coin.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBclycoind\fP, \fBclycoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
